"""rename map to average_precision

Revision ID: 9c4e855d6c74
Revises: fe028af3deed
Create Date: 2026-04-26 16:06:58.912475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c4e855d6c74'
down_revision: Union[str, Sequence[str], None] = 'fe028af3deed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('average_precision', sa.Float(), nullable=True))
    op.drop_column('evaluation_results', 'mean_average_precision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('mean_average_precision', mysql.FLOAT(), nullable=True))
    op.drop_column('evaluation_results', 'average_precision')
    # ### end Alembic commands ###
