"""add news table

Revision ID: bb84d4b21f94
Revises: 1effc502ba74
Create Date: 2026-02-19 20:53:16.766851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb84d4b21f94'
down_revision: Union[str, Sequence[str], None] = '1effc502ba74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tag1', sa.String(length=100), nullable=True),
    sa.Column('tag2', sa.String(length=100), nullable=True),
    sa.Column('tag3', sa.String(length=100), nullable=True),
    sa.Column('tag4', sa.String(length=100), nullable=True),
    sa.Column('tag5', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
