"""remove unused columns from news

Revision ID: cb47370f9ac3
Revises: ee23e53c532e
Create Date: 2026-05-07 13:07:10.887417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb47370f9ac3'
down_revision: Union[str, Sequence[str], None] = 'ee23e53c532e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('link'), table_name='news')
    op.drop_column('news', 'tag5')
    op.drop_column('news', 'tag2')
    op.drop_column('news', 'tag1')
    op.drop_column('news', 'tag3')
    op.drop_column('news', 'source')
    op.drop_column('news', 'tag4')
    op.drop_column('news', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('link', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('news', sa.Column('tag4', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('news', sa.Column('source', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('news', sa.Column('tag3', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('news', sa.Column('tag1', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('news', sa.Column('tag2', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('news', sa.Column('tag5', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('link'), 'news', ['link'], unique=True)
    # ### end Alembic commands ###
