"""create news_feedbacks table

Revision ID: db601c8ba2cb
Revises: 04e7c47d8b1f
Create Date: 2026-02-25 21:27:04.167154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db601c8ba2cb'
down_revision: Union[str, Sequence[str], None] = '04e7c47d8b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
